services:
  - type: web
    name: whatsapp-bot
    env: node
    region: singapore
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /status
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
